import { StyleSheet } from "react-native";
import { ResponsiveStyles } from "./theme";

export const cssStyle = StyleSheet.create<ResponsiveStyles>({
    attributeRowContainer: {
        width: "100%",
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-evenly",
        paddingHorizontal: 4,
        marginVertical: 2,
    },
    card: {
        backgroundColor: "#2a2a2a",
        borderRadius: 16,
        padding: 28,
        marginBottom: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    compactCard: {
        backgroundColor: "#2a2a2a",
        borderRadius: 12,
        padding: 12,
        marginBottom: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 2,
    },
    sectionContainer: {
        backgroundColor: "#333",
        borderRadius: 8,
        padding: 8,
        marginVertical: 4,
        maxWidth: "100%",
    },
    sectionHeaderContainer: {
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        gap: 2,
    },
    sectionItem: {
        flex: 1,
        width: "100%",
        height: 40,
    },
    attributeSectionContainer: {
        width: "100%",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        paddingVertical: 8,
    },
    attribute: {
        minWidth: 50,
        height: 50,
        paddingHorizontal: 8,
        paddingVertical: 4,
        margin: 2,
        justifyContent: "center",
        alignItems: "center",
    },
    clickableStat: {
        backgroundColor: "#444",
        borderRadius: 8,
        padding: 8,
        minWidth: 60,
        justifyContent: "center",
        alignItems: "center",
    },
    headerContainer: {
        flexDirection: "column",
    },

    // Modal responsive styles for phone
    modalView: {
        width: "95%",
        maxWidth: "95%",
        maxHeight: "90%",
        backgroundColor: "#2a2a2a",
        borderRadius: 16,
        padding: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 3.84,
        elevation: 5,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.7)",
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#444",
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: "600",
        color: "#f0f0f0",
        flex: 1,
    },
    modalContent: {
        flex: 1,
        paddingBottom: 8,
    },
    modalButtons: {
        flexDirection: "row",
        justifyContent: "flex-end",
        gap: 12,
        marginTop: 16,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: "#444",
    },
    modalTable: {
        padding: 8,
        backgroundColor: "#333",
        borderRadius: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 1,
    },
    modalTableText: {
        fontSize: 11,
        color: "#f0f0f0",
    },
    modal: {},
    modalCloseButton: {},
    modalFooter: {},
});
